<?php

namespace Database\Seeders;

use App\Models\Challenge;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChallengeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = date('m-d-Y');

        $data = [
            [
                'date' => $date,
                'hour' => 24,
                'minute' => 0,
                'title' => "Win 3 Games within 24 Hrs",
                'games' => 3,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 2,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 24,
                'minute' => 0,
                'title' => "Win 5 Games within 24 Hrs",
                'games' => 5,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 24,
                'minute' => 0,
                'title' => "Win 10 Games within 24 Hrs",
                'games' => 10,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 1,
                'title' => "Win 1 Game under a minute",
                'games' => 10,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
//              'weekly'=>  date('m-d-Y',strtotime('+7 days')),
                'hard_coded'=>  0,
                'visibility'=>  1

            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win the game with all face cards starting on the table",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win a game with no reshuffles",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 1,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win a game starting with no face cards on the table",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1

            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Get 4 queens in a row for extra upgrades",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1

            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 10,
                'title' => "Win 3 games under 10 minutes",
                'games' => 3,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1

            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win 50 games for a free joker",
                'games' => 50,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 2,
                'quantity' => 1,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1

            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win 100 games for a free joker",
                'games' => 100,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 2,
                'quantity' => 1,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win 20 games for a free reshuffle",
                'games' => 20,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 3,
                'quantity' => 1,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  0,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win 5 expert levels",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  null,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Play 300 games to change the deck color to red or blue",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 1,
                'default' => 1,
                'play'=>  300,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Share game with a person to download for free reshuffles",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 3,
                'quantity' => 1,
                'default' => 1,
                'play'=>  0,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win three jokers get an extra reshuffle for free",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 3,
                'quantity' => 1,
                'default' => 1,
                'play'=>  0,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  0
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Connect your Facebook account and receive a free reshuffle",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 3,
                'quantity' => 1,
                'default' => 1,
                'play'=>  0,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  0
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Win a game with no upgrades",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  0,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Play and win 10 games straight with no upgrades",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  10,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
            [
                'date' => $date,
                'hour' => 0,
                'minute' => 0,
                'title' => "Play 100 games",
                'games' => 0,
                'days' =>  json_encode(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']),
                'occurrence' => 'Daily',
                'prize_id' => 1,
                'quantity' => 0,
                'default' => 1,
                'play'=>  100,
                'weekly'=>  null,
                'monthly'=>  null,
                'hard_coded'=>  1,
                'visibility'=>  1
            ],
        ];

        Challenge::insert($data);
    }
}
