@include('home.layout.head')
@if(\Illuminate\Support\Facades\Auth::check())
    @include('home.layout.header2')
@else
    @include('home.layout.header')
@endif
@yield('main')
@include('home.layout.footer')
@include('home.layout.end-page')
