-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2twjHlpTWwmDDqjZ
i2amfdJer2ZhTEuF8lE/V//lVLSgCgYIKoZIzj0DAQehRANCAAT8xtWPrpTyIgX9
qyw0DDENWCCe6c8IQdD1+LJuGaO6ySbgKmVkaQCRMfAWzS7pHVN1MbQxRrll5ozq
4gu1mPB1
-----END PRIVATE KEY-----